### ISSUE TITLE
[reminders] cannot update items

### ISSUE THREAD

**Issue by alfredodeza** [shaunduncan/helga#118]
If a user needs to update a reminder it is forced to delete the current reminder and add it back again.

This workflow is especially painful for recurring reminders that are set in UTC to try an accommodate users that are distributed though different timezones because to re-do the reminder the user needs to remember the exact syntax that was used to create the reminder.

This is an example output of a standup reminder shown from `!reminders list #channel`:

    [531f5f] At 10/13/14 17:15 UTC: 'standup (ping foo bar baz to join)' (Repeat every M,Tu,W,Th,F)

The problem with this output is that a user cannot just copy/paste it with some rewording because the output doesn't match the syntax.

So the next step would mean a user needs to:

    <user> !reminders delete 531f5f
    <helga> no problem

And then add it again with the right syntax:

    <user>  !at 17:15 UTC on #channel  standup (ping foo bar baz to join) repeat MTuWThF

It would be nice to just be able to use the hash and update any part (or all of them), like:

    <user> !reminders update 531f5f standup (ping foo bar baz to join)

Or 

    <user> !reminders update 531f5f #otherchannel
    <user> !reminders update 531f5f repeat MT
    <user> !reminders update 531f5f at 17:00 UTC

**Comment by shaunduncan** [comment]
I've moved the reminders plugin elsewhere with the 1.7.0 release of helga, but I've also made a change there that the hash is actually the full ID of the reminder, so you shouldn't run into this anymore
