### ISSUE TITLE
Channel names truncated to a char?

### ISSUE THREAD

**Issue by fuzzy76** [shaunduncan/helga#140]
My helga truncates channels to a single char. So configuring '#test' makes it join '#'. While 'test' makes it join '#t'. Python 2.7.3 with latest helga from pip. newrelic plugin installed (and seem to be working).

**Comment by fuzzy76** [comment]
My current config:

```
SERVER = {
  'HOST': '193.111.222.33',
  'PORT': 6667,
}
CHANNELS = [
  '#howdy',
  '#helga',
]
NEWRELIC_API_KEY = 'fakeapikey_sincethisispublic'
NEWRELIC_ACCOUNT_ID = 12345
NEWRELIC_WEBHOOK_ANNOUNCE_CHANNEL = "#howdy"
```

**Comment by shaunduncan** [comment]
Thank you for bringing this up. It appears that this is indeed a bug that I'll need to release a patch for. In the meantime, you might be able to work around this issue by changing the channels to tuples:

```
CHANNELS = [
    ('#howdy',),
    ('#helga',),
]
```

Let me know if this will work for now. I'll see about getting a patch out sometime today.

**Comment by shaunduncan** [comment]
I've gone ahead and released a patch update version 1.6.7. I've added some tests for the single string channel setting, so I think this should be fixed now. Could you give the new version a shot and see if that clears up everything for you?

**Comment by fuzzy76** [comment]
Wow, talk about speedy turnaround! Tested the new release, and it worked like a charm. :+1:

**Comment by shaunduncan** [comment]
Great! Thanks again for bringing the issue up!
