### ISSUE TITLE
Split out some of the bundled plugins?

### ISSUE THREAD

**Issue by nrb** [shaunduncan/helga#142]
Some plugins may make sense to split out. For running helga in my environment, the `oneliner` plugin is an annoyance for people in the channel, and I have to remember to manually disable it every time I deploy a new version of my plugin (through ansible-helga).

Also, the oneliner plugin may be better served by an enhanced version of the quips plugin, possibly one that can take multiple responses to the same regex.

Also up for consideration:

* no_more_olga
* wiki_whois
* loljava

**Comment by shaunduncan** [comment]
Perhaps maybe the only ones that should stay:

- help
- manager
- operator
- webhooks
- ping (new for 1.7)

**Comment by shaunduncan** [comment]
The standard plugins now (as of 1.7.0) are help, manager, operator, ping, and webhooks
